# slides-user-story: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up
version: '3'
services:

  app:
    hostname: web
    ports:
      - "80:5000"
    restart: always
    image: python:3.6.1
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
